const mockProfile = {
    "login": "DiegoCuba",
    "id": 63636915,
    "node_id": "MDQ6VXNlcjYzNjM2OTE1",
    "avatar_url": "https://avatars.githubusercontent.com/u/63636915?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DiegoCuba",
    "html_url": "https://github.com/DiegoCuba",
    "followers_url": "https://api.github.com/users/DiegoCuba/followers",
    "following_url": "https://api.github.com/users/DiegoCuba/following{/other_user}",
    "gists_url": "https://api.github.com/users/DiegoCuba/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DiegoCuba/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DiegoCuba/subscriptions",
    "organizations_url": "https://api.github.com/users/DiegoCuba/orgs",
    "repos_url": "https://api.github.com/users/DiegoCuba/repos",
    "events_url": "https://api.github.com/users/DiegoCuba/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DiegoCuba/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Diego Escobar",
    "company": "Dofleini Software",
    "blog": "",
    "location": "Havana Cuba",
    "email": null,
    "hireable": null,
    "bio": "React/Redux Programmer\r\n\r\nMERN/LAMP FullStack Software Engineers",
    "twitter_username": null,
    "public_repos": 29,
    "public_gists": 0,
    "followers": 1,
    "following": 6,
    "created_at": "2020-04-14T08:00:32Z",
    "updated_at": "2021-06-03T10:07:56Z"
}

export default mockProfile