export const mockProfile = {
  login: "DiegoAWS",
  id: 63636915,
  node_id: "MDQ6VXNlcjYzNjM2OTE1",
  avatar_url: "https://avatars.githubusercontent.com/u/63636915?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/DiegoAWS",
  html_url: "https://github.com/DiegoAWS",
  followers_url: "https://api.github.com/users/DiegoAWS/followers",
  following_url: "https://api.github.com/users/DiegoAWS/following{/other_user}",
  gists_url: "https://api.github.com/users/DiegoAWS/gists{/gist_id}",
  starred_url: "https://api.github.com/users/DiegoAWS/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/DiegoAWS/subscriptions",
  organizations_url: "https://api.github.com/users/DiegoAWS/orgs",
  repos_url: "https://api.github.com/users/DiegoAWS/repos",
  events_url: "https://api.github.com/users/DiegoAWS/events{/privacy}",
  received_events_url: "https://api.github.com/users/DiegoAWS/received_events",
  type: "User",
  site_admin: false,
  name: "TESTING TEXT PRESENT",
  company: "Dofleini Software",
  blog: "",
  location: "Havana Cuba",
  email: false,
  hireable: false,
  bio: "React/Redux Programmer\r\n\r\nMERN/LAMP FullStack Software Engineers",
  twitter_username: false,
  public_repos: 29,
  public_gists: 0,
  followers: 1,
  following: 6,
  created_at: "2020-04-14T08:00:32Z",
  updated_at: "2021-06-03T10:07:56Z",
};
